jobs:
- job: tests
  trigger: pull_request
  identifier: singlehost
  branch: main
  targets:
    #- fedora-branched
    - fedora-43
    - centos-stream-10-x86_64
  skip_build: true
  tf_extra_params:
    environments:
      - tmt:
          context:
            target_PR_branch: "main"
            multihost: "no"
