jobs:
- job: tests
  trigger: pull_request
  targets:
    centos-stream-9-x86_64:
      distros: [RHEL-9.1.0-Nightly]
  skip_build: true
  use_internal_tf: true
  tf_extra_params:
    environments:
      - tmt:
          context:
            target_PR_branch: "rhel-9.1.0"
