jobs:
- job: tests
  trigger: pull_request
  branch: fedora-38
  targets:
    - fedora-38
  skip_build: true
  tf_extra_params:
    environments:
      - tmt:
          context:
            target_PR_branch: "fedora-38"
