jobs:
- job: tests
  trigger: pull_request
  identifier: singlehost
  branch: main
  targets:
    #- fedora-branched
    - fedora-all
    - centos-stream-10-x86_64
  skip_build: true
  tf_extra_params:
    environments:
      - tmt:
          context:
            target_PR_branch: "main"
            multihost: "no"
- job: tests
  trigger: pull_request
  identifier: multihost
  branch: main
  targets:
    - centos-stream-10-x86_64
  skip_build: true
  env:
    SYNC_DEBUG: "1"
  use_internal_tf: True
  tf_extra_params:
    test:
      tmt:
        name: "/plans/upstream-keylime-multihost.*"
    environments:
      - tmt:
          context:
            target_PR_branch: "main"
            multihost: "yes"
    settings:
      pipeline:
        type: tmt-multihost
- job: tests
  trigger: pull_request
  identifier: singlehost
  branch: rhel-9-main
  targets:
    - centos-stream-9-x86_64
  skip_build: true
  tf_extra_params:
    environments:
      - tmt:
          context:
            target_PR_branch: "rhel-9-main"
            multihost: "no"
        artifacts:
          - type: repository-file
            id: "https://raw.githubusercontent.com/RedHat-SP-Security/keylime-tests/main/tools/c9s.repo"
- job: tests
  trigger: pull_request
  identifier: multihost
  branch: rhel-9-main
  targets:
    - centos-stream-9-x86_64
  skip_build: true
  env:
    SYNC_DEBUG: "1"
  use_internal_tf: True
  tf_extra_params:
    test:
      tmt:
        name: "/plans/distribution-c9s-keylime-multihost.*"
    environments:
      - tmt:
          context:
            target_PR_branch: "rhel-9-main"
            multihost: "yes"
    settings:
      pipeline:
        type: tmt-multihost
- job: tests
  trigger: pull_request
  identifier: singlehost
  branch: rhel-10-main
  targets:
    - centos-stream-10-x86_64
  skip_build: true
  tf_extra_params:
    environments:
      - tmt:
          context:
            target_PR_branch: "rhel-10-main"
            multihost: "no"
        #artifacts:
        #  - type: repository-file
        #    id: "https://raw.githubusercontent.com/RedHat-SP-Security/keylime-tests/main/tools/c10s.repo"
- job: tests
  trigger: pull_request
  identifier: multihost
  branch: rhel-10-main
  targets:
    - centos-stream-10-x86_64
  skip_build: true
  env:
    SYNC_DEBUG: "1"
  use_internal_tf: True
  tf_extra_params:
    test:
      tmt:
        name: "/plans/distribution-c10s-keylime-multihost.*"
    environments:
      - tmt:
          context:
            target_PR_branch: "rhel-10-main"
            multihost: "yes"
    settings:
      pipeline:
        type: tmt-multihost
- job: tests
  trigger: pull_request
  branch: fedora-main
  targets:
    - fedora-all
  skip_build: true
  tf_extra_params:
    environments:
      - tmt:
          context:
            target_PR_branch: "fedora-main"
