jobs:
- job: tests
  trigger: pull_request
  targets:
    - fedora-all
    - centos-stream-9-x86_64
  skip_build: true
  tf_extra_params:
    environments:
      - tmt:
          context:
            target_PR_branch: "main"
