jobs:
- job: tests
  trigger: pull_request
  metadata:
    targets:
      - fedora-rawhide
      - fedora-37
#    - fedora-all
#    - centos-stream-8-x86_64
#    - centos-stream-9-x86_64
    skip_build: true
