#!/bin/bash
# vim: dict+=/usr/share/beakerlib/dictionary.vim cpt=.,w,b,u,t,i,k
. /usr/share/beakerlib/beakerlib.sh || exit 1

AGENT_ID="d432fbb3-d2f1-4a97-9ef7-75bd81c00000"

rlJournalStart

    rlPhaseStartSetup "Do the keylime setup"
        rlRun 'rlImport "./test-helpers"' || rlDie "cannot import keylime-tests/test-helpers library"
        rlAssertRpm keylime
        rlRun -s "mokutil --sb-state"
        rlAssertGrep "SecureBoot enabled" $rlRun_LOG || rlDie "SecureBoot is not enabled"

        # apply measured boot policy update due to https://github.com/keylime/keylime/issues/1003
        if [ -f /usr/local/lib/python3.10/site-packages/keylime-6.4.0-py3.10.egg/keylime/elchecking/example.py ]; then
            rlLogInfo "Applying measured boot policy fix due to https://github.com/keylime/keylime/issues/1003"
            rlRun "cat example.py > /usr/local/lib/python3.10/site-packages/keylime-6.4.0-py3.10.egg/keylime/elchecking/example.py"
        fi

        # update /etc/keylime.conf
        limeBackupConfig
        rlRun "limeUpdateConf tenant require_ek_cert False"
        rlRun "limeUpdateConf cloud_verifier measured_boot_policy_name accept-all"
        rlRun "limeUpdateConf cloud_verifier revocation_notifier False"
        rlRun "limeUpdateConf cloud_agent listen_notifications False"
        # start keylime_verifier
        rlRun "limeStartVerifier"
        rlRun "limeWaitForVerifier"
        rlRun "limeStartRegistrar"
        rlRun "limeWaitForRegistrar"
        rlRun "limeStartAgent"
        rlRun "limeWaitForAgentRegistration ${AGENT_ID}"
        # create allowlist and excludelist
        limeCreateTestLists
    rlPhaseEnd

    rlPhaseStartTest "Try adding agent with PRC15 configured in tpm_policy"
        rlRun "echo '{}' > mb_refstate.txt"
        rlRun -s "lime_keylime_tenant -u $AGENT_ID --verify --allowlist allowlist.txt --exclude excludelist.txt -f excludelist.txt -c add --mb_refstate mb_refstate.txt" 1
        rlAssertGrep 'ERROR - WARNING: PCR 15 is specified in "tpm_policy", but will in fact be used by measured boot. Please remove it from policy' $rlRun_LOG
    rlPhaseEnd

    rlPhaseStartTest "Add agent with tpm_policy unset"
        rlRun "limeUpdateConf tenant tpm_policy {}"
        rlRun -s "lime_keylime_tenant -u $AGENT_ID --verify --allowlist allowlist.txt --exclude excludelist.txt -f excludelist.txt -c add --mb_refstate mb_refstate.txt"
        rlRun "limeWaitForAgentStatus $AGENT_ID 'Get Quote'"
        rlRun -s "lime_keylime_tenant -c cvlist"
        rlAssertGrep "{'code': 200, 'status': 'Success', 'results': {'uuids':.*'$AGENT_ID'" $rlRun_LOG -E
    rlPhaseEnd

    rlPhaseStartTest "Configure verifier to use elchecking/example measured boot policy, restart and re-register agent"
        rlRun "lime_keylime_tenant -u $AGENT_ID -c delete"
        rlRun "lime_keylime_tenant -u $AGENT_ID -c regdelete"
        rlRun "limeStopAgent"
        rlRun "limeStopVerifier"
        sleep 5
        rlRun "limeUpdateConf cloud_verifier measured_boot_policy_name example"
	rlRun "limeStartVerifier"
        rlRun "limeWaitForVerifier"
        rlRun "limeStartAgent"
        rlRun "limeWaitForAgentRegistration ${AGENT_ID}"
    rlPhaseEnd

    rlPhaseStartTest "Add agent with tpm_policy generated by scripts/create_mb_refstate"
        rlRun "curl -O 'https://raw.githubusercontent.com/keylime/keylime/master/scripts/create_mb_refstate' && chmod a+x create_mb_refstate"
        rlRun "./create_mb_refstate /sys/kernel/security/tpm0/binary_bios_measurements mb_refstate2.txt"
        rlRun -s "lime_keylime_tenant -u $AGENT_ID --verify --allowlist allowlist.txt --exclude excludelist.txt -f excludelist.txt -c add --mb_refstate mb_refstate2.txt"
        rlRun "limeWaitForAgentStatus $AGENT_ID 'Get Quote'"
        rlRun -s "lime_keylime_tenant -c cvlist"
        rlAssertGrep "{'code': 200, 'status': 'Success', 'results': {'uuids':.*'$AGENT_ID'" $rlRun_LOG -E
    rlPhaseEnd

    rlPhaseStartTest "Restart and re-register agent"
        rlRun "lime_keylime_tenant -u $AGENT_ID -c delete"
        rlRun "lime_keylime_tenant -u $AGENT_ID -c regdelete"
        rlRun "limeStopAgent"
        sleep 5
        rlRun "limeStartAgent"
        rlRun "limeWaitForAgentRegistration ${AGENT_ID}"
    rlPhaseEnd

    rlPhaseStartTest "Add agent with incorrect tpm_policy"
        rlRun "sed 's/0x[1-9a-f]/0x0/g' mb_refstate2.txt > mb_refstate3.txt"
        rlRun -s "lime_keylime_tenant -u $AGENT_ID --verify --allowlist allowlist.txt --exclude excludelist.txt -f excludelist.txt -c add --mb_refstate mb_refstate3.txt"
        rlRun "limeWaitForAgentStatus $AGENT_ID 'Tenant Quote Failed'"
    rlPhaseEnd

    rlPhaseStartCleanup "Do the keylime cleanup"
        rlRun "limeStopAgent"
        rlRun "limeStopRegistrar"
        rlRun "limeStopVerifier"
        limeLogfileSubmit $(limeVerifierLogfile)
        limeLogfileSubmit $(limeRegistrarLogfile)
        limeLogfileSubmit $(limeAgentLogfile)
        limeClearData
        limeRestoreConfig
    rlPhaseEnd

rlJournalEnd
