#!/bin/bash
# vim: dict+=/usr/share/beakerlib/dictionary.vim cpt=.,w,b,u,t,i,k
. /usr/share/beakerlib/beakerlib.sh || exit 1

AGENT_ID="d432fbb3-d2f1-4a97-9ef7-75bd81c00000"

rlJournalStart

    rlPhaseStartSetup "Do the keylime setup"
        rlRun 'rlImport "./test-helpers"' || rlDie "cannot import keylime-tests/test-helpers library"
        rlAssertRpm keylime
        # update /etc/keylime.conf
        limeBackupConfig
        rlRun "limeUpdateConf tenant require_ek_cert False"
        rlRun "limeUpdateConf verifier measured_boot_policy_name accept-all"
        rlRun "limeUpdateConf revocations enabled_revocation_notifications '[]'"
        rlRun "limeUpdateConf agent enable_revocation_notifications false"
        # start keylime_verifier
        rlRun "limeStartVerifier"
        rlRun "limeWaitForVerifier"
        rlRun "limeStartRegistrar"
        rlRun "limeWaitForRegistrar"
        rlRun "limeStartAgent"
        rlRun "limeWaitForAgentRegistration ${AGENT_ID}"
        # create allowlist and excludelist
        limeCreateTestPolicy
    rlPhaseEnd

    rlPhaseStartTest "Try adding agent with PRC15 configured in tpm_policy"
        # do not die if SecureBoot not enabled but make sure the test fails
        rlRun -s "mokutil --sb-state"
        rlAssertGrep "SecureBoot enabled" $rlRun_LOG || NO_SB_PARAM="--without-secureboot"
        TPM_POLICY='{"15":["0000000000000000000000000000000000000000","0000000000000000000000000000000000000000000000000000000000000000","000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"]}'
        rlRun "echo '{}' > mb_refstate.txt"
        rlRun -s "limeCtl agent add $AGENT_ID --verify --tpm-policy '${TPM_POLICY}' --runtime-policy policy.json --mb-refstate mb_refstate.txt" 1
        rlAssertGrep 'ERROR - WARNING: PCR 15 is specified in "tpm_policy", but will in fact be used by measured boot. Please remove it from policy' $rlRun_LOG
    rlPhaseEnd

    rlPhaseStartTest "Add agent with empty tpm_policy"
        rlRun -s "limeCtl agent add $AGENT_ID --verify --tpm-policy '{}' --runtime-policy policy.json --mb-refstate mb_refstate.txt"
        rlRun "limeWaitForAgentStatus --field attestation_status $AGENT_ID 'PASS'"
        rlRun -s "limeCtl agent list"
        rlRun "limeAssertJsonField $rlRun_LOG code=200 status=Success uuids=$AGENT_ID"
    rlPhaseEnd

    rlPhaseStartTest "Configure verifier to use elchecking/example measured boot policy, restart and re-register agent"
        rlRun "limeCtl agent remove $AGENT_ID"
        rlRun "keylime_tenant -u $AGENT_ID -c regdelete"
        rlRun "limeStopAgent"
        rlRun "limeStopVerifier"
        sleep 5
        rlRun "limeUpdateConf verifier measured_boot_policy_name example"
	rlRun "limeStartVerifier"
        rlRun "limeWaitForVerifier"
        rlRun "limeStartAgent"
        rlRun "limeWaitForAgentRegistration ${AGENT_ID}"
    rlPhaseEnd

    MB_POLICIES=()
    rlPhaseStartTest "Create measured boot policy"
        # Use keylime-policy to create the measured boot policy
        rlRun "keylime-policy create measured-boot -e $NO_SB_PARAM /sys/kernel/security/tpm0/binary_bios_measurements -o mb_refstate3.txt"
        MB_POLICIES+=("mb_refstate3.txt")
    rlPhaseEnd

    for mb_policy in "${MB_POLICIES[@]}"; do
        rlPhaseStartTest "Add agent with tpm_policy generated by create_mb_refstate script"
            rlRun -s "limeCtl agent add $AGENT_ID --verify --tpm-policy '{}' --runtime-policy policy.json --mb-refstate $mb_policy"
            rlRun "limeWaitForAgentStatus --field attestation_status $AGENT_ID 'PASS'"
            rlRun -s "limeCtl agent list"
            rlRun "limeAssertJsonField $rlRun_LOG code=200 status=Success uuids=$AGENT_ID"
        rlPhaseEnd

        rlPhaseStartTest "Restart and re-register agent"
            rlRun "limeCtl agent remove $AGENT_ID"
            rlRun "keylime_tenant -u $AGENT_ID -c regdelete"
            rlRun "limeStopAgent"
            sleep 5
            rlRun "limeStartAgent"
            rlRun "limeWaitForAgentRegistration ${AGENT_ID}"
        rlPhaseEnd
    done

    rlPhaseStartTest "Add agent with incorrect tpm_policy"
        rlRun "sed 's/0x[1-9a-f]/0x0/g' mb_refstate3.txt > modified_mb_refstate.txt"
        rlRun -s "limeCtl agent add $AGENT_ID --verify --tpm-policy '{}' --runtime-policy policy.json --mb-refstate modified_mb_refstate.txt" 1
        rlRun "limeWaitForAgentStatus $AGENT_ID 'Tenant Quote Failed'"
    rlPhaseEnd

    rlPhaseStartCleanup "Do the keylime cleanup"
        rlRun "limeStopAgent"
        rlRun "limeStopRegistrar"
        rlRun "limeStopVerifier"
        limeSubmitCommonLogs
        limeClearData
        limeRestoreConfig
    rlPhaseEnd

rlJournalEnd
