FROM quay.io/centos/centos:stream9-development
RUN \
  rm -f /etc/yum.repos.d/centos.repo && \
  curl -o /etc/yum.repos.d/c9s.repo 'https://raw.githubusercontent.com/RedHat-SP-Security/keylime-tests/main/tools/c9s.repo' && \
  cat /etc/yum.repos.d/* && \
  dnf install -y keylime which && \
  dnf clean all
