name: Differential ShellCheck
on:
  push:
    branches: [ main, fedora-*, rhel-* ]
  pull_request:
    branches: [ main, fedora-*, rhel-* ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    
    permissions:
      security-events: write

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: ShellCheck
        name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ always() }}
        name: Upload artifact with ShellCheck defects in SARIF format
        uses: actions/upload-artifact@v4
        with:
          name: Differential ShellCheck SARIF
          path: ${{ steps.ShellCheck.outputs.sarif }}
